import type { Fir, Suspect, PoliceStation, Hotspot, NetworkNode } from "./use-ksp-data";

export const MOCK_POLICE_STATIONS: PoliceStation[] = [
  {
    id: "ps-1",
    name: "Whitefield PS",
    district: "Bengaluru Urban",
    latitude: 12.9698,
    longitude: 77.75,
    jurisdiction: "Whitefield / ITPL corridor, Bengaluru East Division",
  },
  {
    id: "ps-2",
    name: "Koramangala PS",
    district: "Bengaluru Urban",
    latitude: 12.9352,
    longitude: 77.6245,
    jurisdiction: "Koramangala 1st-8th Block, Bengaluru South East Division",
  },
  {
    id: "ps-3",
    name: "Cybercrime PS",
    district: "Bengaluru Urban",
    latitude: 12.9878,
    longitude: 77.599,
    jurisdiction: "CID Cybercrime, statewide cyber offences",
  },
  {
    id: "ps-4",
    name: "Yeshwanthpur PS",
    district: "Bengaluru Urban",
    latitude: 13.023,
    longitude: 77.55,
    jurisdiction: "Yeshwanthpur industrial + railway belt",
  },
  {
    id: "ps-5",
    name: "HSR Layout PS",
    district: "Bengaluru Urban",
    latitude: 12.9116,
    longitude: 77.6389,
    jurisdiction: "HSR Layout Sectors 1-7",
  },
  {
    id: "ps-6",
    name: "Devaraja PS",
    district: "Mysuru",
    latitude: 12.3072,
    longitude: 76.6549,
    jurisdiction: "Devaraja Market and city core",
  },
  {
    id: "ps-7",
    name: "V.V. Puram PS",
    district: "Mysuru",
    latitude: 12.2958,
    longitude: 76.6394,
    jurisdiction: "Vidyaranyapuram / south Mysuru",
  },
  {
    id: "ps-8",
    name: "Nazarbad PS",
    district: "Mysuru",
    latitude: 12.3005,
    longitude: 76.665,
    jurisdiction: "Nazarbad, Bannimantap approach roads",
  },
  {
    id: "ps-9",
    name: "Bunder PS",
    district: "Mangaluru",
    latitude: 12.8617,
    longitude: 74.832,
    jurisdiction: "Old Port / Bunder trading belt",
  },
  {
    id: "ps-10",
    name: "Pandeshwar PS",
    district: "Mangaluru",
    latitude: 12.865,
    longitude: 74.842,
    jurisdiction: "Pandeshwar, State Bank, Hampankatta",
  },
  {
    id: "ps-11",
    name: "Kadri PS",
    district: "Mangaluru",
    latitude: 12.8894,
    longitude: 74.856,
    jurisdiction: "Kadri, Bejai, Mallikatte",
  },
  {
    id: "ps-12",
    name: "Vidyanagar PS",
    district: "Hubballi-Dharwad",
    latitude: 15.355,
    longitude: 75.13,
    jurisdiction: "Vidyanagar, Hubballi north",
  },
  {
    id: "ps-13",
    name: "Camp PS",
    district: "Belagavi",
    latitude: 15.857,
    longitude: 74.506,
    jurisdiction: "Belagavi Camp / cantonment",
  },
  {
    id: "ps-14",
    name: "Brahmapur PS",
    district: "Kalaburagi",
    latitude: 17.335,
    longitude: 76.834,
    jurisdiction: "Brahmapur, Kalaburagi city",
  },
];

export const MOCK_SUSPECTS: Suspect[] = [
  {
    id: "s-1",
    suspect_code: "S-1042",
    name: "Ravi Kumar",
    aliases: ["Chikka", "Ravi Anna"],
    district: "Bengaluru Urban",
    station_name: "Whitefield PS",
    phone_numbers: ["+91-98450-77231", "+91-73490-11208"],
    vehicle: "KA-05-MJ-4471 (Pulsar 220)",
    mo_description:
      "Two-wheeler theft using duplicated master key between 02:00-04:00; vehicles moved to Hoskote for re-stamping.",
    mo_tags: ["Master Key", "Night Window", "Re-stamping"],
    risk_score: 92,
    cross_jurisdiction: ["Bengaluru Urban", "Mysuru", "Kalaburagi"],
    status: "BOLO Active",
  },
  {
    id: "s-2",
    suspect_code: "S-2213",
    name: "Imran Sheikh",
    aliases: ["Choti", "Imran Bhai"],
    district: "Mysuru",
    station_name: "Devaraja PS",
    phone_numbers: ["+91-90080-42014"],
    vehicle: "KA-09-HG-2210 (Splendor)",
    mo_description:
      "Chain snatching on pillion-ride two-wheeler near temple and market exits during evening prayer hours.",
    mo_tags: ["Pillion Snatch", "Evening Window"],
    risk_score: 81,
    cross_jurisdiction: ["Mysuru", "Bengaluru Urban"],
    status: "Under Surveillance",
  },
  {
    id: "s-3",
    suspect_code: "S-3390",
    name: "Prakash Devadiga",
    aliases: ["PD", "Prakash Bunder"],
    district: "Mangaluru",
    station_name: "Bunder PS",
    phone_numbers: ["+91-70220-98887", "+91-88610-33450"],
    vehicle: null,
    mo_description:
      "Extortion calls to small traders using rotating pre-paid SIMs; collection through fish-market intermediaries.",
    mo_tags: ["Rotating SIM", "Trader Extortion"],
    risk_score: 88,
    cross_jurisdiction: ["Mangaluru", "Udupi"],
    status: "Chargesheeted",
  },
  {
    id: "s-4",
    suspect_code: "S-4471",
    name: "Satish Murthy",
    aliases: ["Sattu"],
    district: "Bengaluru Urban",
    station_name: "Cybercrime PS",
    phone_numbers: ["+91-96320-40402"],
    vehicle: null,
    mo_description:
      "OTP phishing via fake KYC calls impersonating bank officials; mule accounts opened in Mysuru branches.",
    mo_tags: ["Fake KYC", "Mule Accounts"],
    risk_score: 76,
    cross_jurisdiction: ["Bengaluru Urban", "Mysuru"],
    status: "Under Investigation",
  },
  {
    id: "s-5",
    suspect_code: "S-5514",
    name: "Nagesh Gowda",
    aliases: ["Naga", "Gowda"],
    district: "Bengaluru Urban",
    station_name: "Koramangala PS",
    phone_numbers: ["+91-99860-21174"],
    vehicle: "KA-03-EF-9012 (Activa)",
    mo_description:
      "Late-night chain snatching on unlit stretches around pub districts, exiting via service roads.",
    mo_tags: ["Unlit Stretch", "Pillion Snatch"],
    risk_score: 79,
    cross_jurisdiction: ["Bengaluru Urban"],
    status: "Under Surveillance",
  },
  {
    id: "s-6",
    suspect_code: "S-6620",
    name: "Rehman Pasha",
    aliases: ["Rehu"],
    district: "Mysuru",
    station_name: "Nazarbad PS",
    phone_numbers: ["+91-97410-55620"],
    vehicle: "KA-09-KA-1120 (Pulsar 150)",
    mo_description:
      "Residential burglary of locked houses during festival travel season, entry through rear ventilators.",
    mo_tags: ["Rear Entry", "Festival Season"],
    risk_score: 73,
    cross_jurisdiction: ["Mysuru", "Mandya"],
    status: "BOLO Active",
  },
  {
    id: "s-7",
    suspect_code: "S-7702",
    name: "Suresh Shetty",
    aliases: ["Shetty", "Sura"],
    district: "Mangaluru",
    station_name: "Kadri PS",
    phone_numbers: ["+91-94480-77002"],
    vehicle: "KA-19-P-3388 (Bolero)",
    mo_description:
      "Commercial godown burglary with transport arranged in advance; targets electronics consignments.",
    mo_tags: ["Godown", "Transport Ready"],
    risk_score: 84,
    cross_jurisdiction: ["Mangaluru", "Hubballi-Dharwad"],
    status: "Under Investigation",
  },
  {
    id: "s-8",
    suspect_code: "S-8891",
    name: "Lokesh Bhat",
    aliases: ["Loki"],
    district: "Mangaluru",
    station_name: "Pandeshwar PS",
    phone_numbers: ["+91-80950-18891"],
    vehicle: null,
    mo_description:
      "Investment-app cyber fraud targeting NRI families on the coastal belt; funds routed to crypto wallets.",
    mo_tags: ["Investment App", "Crypto Routing"],
    risk_score: 69,
    cross_jurisdiction: ["Mangaluru", "Bengaluru Urban"],
    status: "Under Surveillance",
  },
];

export const MOCK_FIRS: Fir[] = [
  {
    id: "fir-1",
    fir_number: "FIR/WFD/2026/2211",
    incident_date: "2026-07-19",
    incident_hour: 3,
    district: "Bengaluru Urban",
    station_name: "Whitefield PS",
    crime_type: "Vehicle Theft",
    status: "Under Investigation",
    loss_value: 118000,
    locality: "ITPL Main Road",
    latitude: 12.9852,
    longitude: 77.736,
    summary: "Pulsar 220 lifted from apartment basement; master-key entry, no glass damage.",
    suspect_code: "S-1042",
    investigating_officer: "PSI M. Ramesh",
  },
  {
    id: "fir-2",
    fir_number: "FIR/WFD/2026/2245",
    incident_date: "2026-07-21",
    incident_hour: 2,
    district: "Bengaluru Urban",
    station_name: "Whitefield PS",
    crime_type: "Vehicle Theft",
    status: "Under Investigation",
    loss_value: 92000,
    locality: "Kundalahalli Gate",
    latitude: 12.962,
    longitude: 77.715,
    summary: "Two-wheeler theft from service road, CCTV shows same MO as FIR/WFD/2026/2211.",
    suspect_code: "S-1042",
    investigating_officer: "PSI M. Ramesh",
  },
  {
    id: "fir-3",
    fir_number: "FIR/WFD/2026/2260",
    incident_date: "2026-07-14",
    incident_hour: 22,
    district: "Bengaluru Urban",
    station_name: "Whitefield PS",
    crime_type: "Cyber Fraud",
    status: "Under Investigation",
    loss_value: 245000,
    locality: "Hope Farm Junction",
    latitude: 12.9905,
    longitude: 77.748,
    summary: "Complainant lost funds after fake KYC verification call from spoofed bank number.",
    suspect_code: "S-4471",
    investigating_officer: "Insp. L. Kariappa",
  },
  {
    id: "fir-4",
    fir_number: "FIR/KOR/2026/0442",
    incident_date: "2026-07-18",
    incident_hour: 21,
    district: "Bengaluru Urban",
    station_name: "Koramangala PS",
    crime_type: "Chain Snatching",
    status: "Under Investigation",
    loss_value: 86000,
    locality: "80 Feet Road, 4th Block",
    latitude: 12.9345,
    longitude: 77.627,
    summary: "Gold chain snatched from pedestrian by pillion rider on unlit stretch.",
    suspect_code: "S-5514",
    investigating_officer: "PSI R. Devaraj",
  },
  {
    id: "fir-5",
    fir_number: "FIR/KOR/2026/0451",
    incident_date: "2026-07-22",
    incident_hour: 23,
    district: "Bengaluru Urban",
    station_name: "Koramangala PS",
    crime_type: "Chain Snatching",
    status: "Under Investigation",
    loss_value: 74000,
    locality: "5th Block Service Road",
    latitude: 12.937,
    longitude: 77.621,
    summary: "Second snatching in same beat within four days; identical exit route.",
    suspect_code: "S-5514",
    investigating_officer: "PSI R. Devaraj",
  },
  {
    id: "fir-6",
    fir_number: "FIR/KOR/2026/0460",
    incident_date: "2026-07-09",
    incident_hour: 19,
    district: "Bengaluru Urban",
    station_name: "Koramangala PS",
    crime_type: "Assault",
    status: "Chargesheeted",
    loss_value: 0,
    locality: "Jyoti Nivas Circle",
    latitude: 12.933,
    longitude: 77.618,
    summary: "Group assault following traffic altercation outside commercial complex.",
    suspect_code: null,
    investigating_officer: "PSI R. Devaraj",
  },
  {
    id: "fir-7",
    fir_number: "FIR/CYB/2026/1120",
    incident_date: "2026-07-11",
    incident_hour: 15,
    district: "Bengaluru Urban",
    station_name: "Cybercrime PS",
    crime_type: "Cyber Fraud",
    status: "Under Investigation",
    loss_value: 680000,
    locality: "Infantry Road",
    latitude: 12.988,
    longitude: 77.5985,
    summary: "OTP phishing on senior citizen; funds withdrawn via mule accounts in Mysuru.",
    suspect_code: "S-4471",
    investigating_officer: "Insp. S. Bhaskar",
  },
  {
    id: "fir-8",
    fir_number: "FIR/CYB/2026/1201",
    incident_date: "2026-07-20",
    incident_hour: 12,
    district: "Bengaluru Urban",
    station_name: "Cybercrime PS",
    crime_type: "Cyber Fraud",
    status: "Under Investigation",
    loss_value: 1250000,
    locality: "Ali Askar Road",
    latitude: 12.991,
    longitude: 77.594,
    summary: "Nine complainants linked to same fake-KYC call centre; consolidated investigation.",
    suspect_code: "S-4471",
    investigating_officer: "Insp. S. Bhaskar",
  },
  {
    id: "fir-9",
    fir_number: "FIR/CYB/2026/1215",
    incident_date: "2026-07-23",
    incident_hour: 11,
    district: "Bengaluru Urban",
    station_name: "Cybercrime PS",
    crime_type: "Cyber Fraud",
    status: "Under Investigation",
    loss_value: 430000,
    locality: "Cunningham Road",
    latitude: 12.9925,
    longitude: 77.596,
    summary: "Investment-app fraud with returns dashboard; payouts stopped after third deposit.",
    suspect_code: "S-8891",
    investigating_officer: "Insp. S. Bhaskar",
  },
  {
    id: "fir-10",
    fir_number: "FIR/YPR/2026/1188",
    incident_date: "2026-07-06",
    incident_hour: 4,
    district: "Bengaluru Urban",
    station_name: "Yeshwanthpur PS",
    crime_type: "Vehicle Theft",
    status: "Detected",
    loss_value: 88000,
    locality: "Goods Shed Road",
    latitude: 13.021,
    longitude: 77.552,
    summary: "Recovered motorcycle traced to Hoskote re-stamping shed.",
    suspect_code: "S-1042",
    investigating_officer: "PSI A. Nayak",
  },
  {
    id: "fir-11",
    fir_number: "FIR/YPR/2026/1194",
    incident_date: "2026-07-16",
    incident_hour: 1,
    district: "Bengaluru Urban",
    station_name: "Yeshwanthpur PS",
    crime_type: "Burglary",
    status: "Under Investigation",
    loss_value: 310000,
    locality: "Rajajinagar Industrial Area",
    latitude: 13.018,
    longitude: 77.548,
    summary: "Godown shutter cut; electronics consignment removed in tempo.",
    suspect_code: "S-7702",
    investigating_officer: "PSI A. Nayak",
  },
  {
    id: "fir-12",
    fir_number: "FIR/HSR/2026/0771",
    incident_date: "2026-07-13",
    incident_hour: 2,
    district: "Bengaluru Urban",
    station_name: "HSR Layout PS",
    crime_type: "Burglary",
    status: "Under Investigation",
    loss_value: 420000,
    locality: "Sector 2, 27th Main",
    latitude: 12.912,
    longitude: 77.64,
    summary: "Locked residence burgled while family travelling; rear ventilator entry.",
    suspect_code: null,
    investigating_officer: "PSI K. Shivanna",
  },
  {
    id: "fir-13",
    fir_number: "FIR/HSR/2026/0780",
    incident_date: "2026-07-24",
    incident_hour: 20,
    district: "Bengaluru Urban",
    station_name: "HSR Layout PS",
    crime_type: "Chain Snatching",
    status: "Under Investigation",
    loss_value: 56000,
    locality: "Agara Lake Road",
    latitude: 12.918,
    longitude: 77.635,
    summary: "Chain snatched near lake walking path during evening hours.",
    suspect_code: "S-5514",
    investigating_officer: "PSI K. Shivanna",
  },
  {
    id: "fir-14",
    fir_number: "FIR/DVR/2026/0781",
    incident_date: "2026-07-17",
    incident_hour: 19,
    district: "Mysuru",
    station_name: "Devaraja PS",
    crime_type: "Chain Snatching",
    status: "Under Investigation",
    loss_value: 94000,
    locality: "Devaraja Market East Gate",
    latitude: 12.3078,
    longitude: 76.654,
    summary: "Chain snatching at market exit during evening prayer footfall.",
    suspect_code: "S-2213",
    investigating_officer: "PSI H. Manjunath",
  },
  {
    id: "fir-15",
    fir_number: "FIR/DVR/2026/0790",
    incident_date: "2026-07-20",
    incident_hour: 20,
    district: "Mysuru",
    station_name: "Devaraja PS",
    crime_type: "Chain Snatching",
    status: "Under Investigation",
    loss_value: 67000,
    locality: "Sayyaji Rao Road",
    latitude: 12.309,
    longitude: 76.652,
    summary: "Pillion rider snatched mangalsutra; escaped through market lanes.",
    suspect_code: "S-2213",
    investigating_officer: "PSI H. Manjunath",
  },
  {
    id: "fir-16",
    fir_number: "FIR/VVP/2026/0122",
    incident_date: "2026-07-15",
    incident_hour: 22,
    district: "Mysuru",
    station_name: "V.V. Puram PS",
    crime_type: "Chain Snatching",
    status: "Chargesheeted",
    loss_value: 48000,
    locality: "Vidyaranyapuram Circle",
    latitude: 12.296,
    longitude: 76.64,
    summary: "Snatching near bus stop; accused identified through CCTV and arrested.",
    suspect_code: "S-2213",
    investigating_officer: "PSI G. Suma",
  },
  {
    id: "fir-17",
    fir_number: "FIR/NZB/2026/0455",
    incident_date: "2026-07-10",
    incident_hour: 2,
    district: "Mysuru",
    station_name: "Nazarbad PS",
    crime_type: "Burglary",
    status: "Under Investigation",
    loss_value: 180000,
    locality: "Bannimantap Extension",
    latitude: 12.302,
    longitude: 76.669,
    summary: "Rear ventilator entry, same MO as Ramakrishna Nagar case.",
    suspect_code: "S-6620",
    investigating_officer: "Insp. P. Bhat",
  },
  {
    id: "fir-18",
    fir_number: "FIR/BUN/2026/0339",
    incident_date: "2026-07-19",
    incident_hour: 13,
    district: "Mangaluru",
    station_name: "Bunder PS",
    crime_type: "Organized Extortion",
    status: "Under Investigation",
    loss_value: 350000,
    locality: "Old Port Bunder",
    latitude: 12.862,
    longitude: 74.831,
    summary: "Fish-market trader received extortion calls from rotating SIMs.",
    suspect_code: "S-3390",
    investigating_officer: "Insp. V. Naik",
  },
  {
    id: "fir-19",
    fir_number: "FIR/PDS/2026/0219",
    incident_date: "2026-07-24",
    incident_hour: 10,
    district: "Mangaluru",
    station_name: "Pandeshwar PS",
    crime_type: "Cyber Fraud",
    status: "Under Investigation",
    loss_value: 520000,
    locality: "State Bank Circle",
    latitude: 12.864,
    longitude: 74.84,
    summary: "NRI family defrauded through investment app; funds routed to crypto wallets.",
    suspect_code: "S-8891",
    investigating_officer: "PSI D. Fernandes",
  },
  {
    id: "fir-20",
    fir_number: "FIR/KDR/2026/0090",
    incident_date: "2026-07-16",
    incident_hour: 2,
    district: "Mangaluru",
    station_name: "Kadri PS",
    crime_type: "Burglary",
    status: "Under Investigation",
    loss_value: 610000,
    locality: "Kadri Temple Road",
    latitude: 12.889,
    longitude: 74.857,
    summary: "Electronics godown burgled; transport arranged before offence.",
    suspect_code: "S-7702",
    investigating_officer: "PSI R. Poojary",
  },
  {
    id: "fir-21",
    fir_number: "FIR/VDN/2026/0512",
    incident_date: "2026-07-15",
    incident_hour: 3,
    district: "Hubballi-Dharwad",
    station_name: "Vidyanagar PS",
    crime_type: "Burglary",
    status: "Under Investigation",
    loss_value: 230000,
    locality: "Vidyanagar 2nd Cross",
    latitude: 15.356,
    longitude: 75.132,
    summary: "Shop burglary; stolen consignment matched Mangaluru godown case.",
    suspect_code: "S-7702",
    investigating_officer: "PSI B. Hiremath",
  },
  {
    id: "fir-22",
    fir_number: "FIR/CMP/2026/0288",
    incident_date: "2026-07-12",
    incident_hour: 20,
    district: "Belagavi",
    station_name: "Camp PS",
    crime_type: "Assault",
    status: "Under Investigation",
    loss_value: 0,
    locality: "Camp Main Road",
    latitude: 15.858,
    longitude: 74.507,
    summary: "Public brawl near cantonment market; three persons injured.",
    suspect_code: null,
    investigating_officer: "PSI N. Patil",
  },
  {
    id: "fir-23",
    fir_number: "FIR/BRP/2026/0177",
    incident_date: "2026-07-17",
    incident_hour: 2,
    district: "Kalaburagi",
    station_name: "Brahmapur PS",
    crime_type: "Burglary",
    status: "Under Investigation",
    loss_value: 160000,
    locality: "Brahmapur Colony",
    latitude: 17.336,
    longitude: 76.835,
    summary: "Commercial break-in during sparse patrol window 02:00-04:00.",
    suspect_code: "S-1042",
    investigating_officer: "PSI S. Hosamani",
  },
];

export const MOCK_HOTSPOTS: Hotspot[] = [
  {
    id: "hs-1",
    name: "Whitefield / ITPL Corridor",
    district: "Bengaluru Urban",
    station_name: "Whitefield PS",
    latitude: 12.9698,
    longitude: 77.75,
    intensity: 0.94,
    dominant_crime_type: "Cyber Fraud",
    incident_count: 214,
    peak_window: "Fri 20:00 - Sat 01:00",
  },
  {
    id: "hs-2",
    name: "Koramangala Pub Belt",
    district: "Bengaluru Urban",
    station_name: "Koramangala PS",
    latitude: 12.9352,
    longitude: 77.6245,
    intensity: 0.87,
    dominant_crime_type: "Chain Snatching",
    incident_count: 176,
    peak_window: "Fri 22:00 - Sat 02:00",
  },
  {
    id: "hs-3",
    name: "Bengaluru Central Cyber Cell",
    district: "Bengaluru Urban",
    station_name: "Cybercrime PS",
    latitude: 12.9878,
    longitude: 77.599,
    intensity: 0.9,
    dominant_crime_type: "Cyber Fraud",
    incident_count: 322,
    peak_window: "Weekdays 11:00 - 16:00",
  },
  {
    id: "hs-4",
    name: "HSR Layout Sectors",
    district: "Bengaluru Urban",
    station_name: "HSR Layout PS",
    latitude: 12.9116,
    longitude: 77.6389,
    intensity: 0.71,
    dominant_crime_type: "Burglary",
    incident_count: 98,
    peak_window: "Tue 01:00 - 04:00",
  },
  {
    id: "hs-5",
    name: "Yeshwanthpur Industrial Belt",
    district: "Bengaluru Urban",
    station_name: "Yeshwanthpur PS",
    latitude: 13.023,
    longitude: 77.55,
    intensity: 0.66,
    dominant_crime_type: "Vehicle Theft",
    incident_count: 87,
    peak_window: "Daily 02:00 - 05:00",
  },
  {
    id: "hs-6",
    name: "Devaraja Market Core",
    district: "Mysuru",
    station_name: "Devaraja PS",
    latitude: 12.3072,
    longitude: 76.6549,
    intensity: 0.85,
    dominant_crime_type: "Chain Snatching",
    incident_count: 132,
    peak_window: "Daily 18:00 - 21:00",
  },
  {
    id: "hs-7",
    name: "Nazarbad - Bannimantap",
    district: "Mysuru",
    station_name: "Nazarbad PS",
    latitude: 12.3005,
    longitude: 76.665,
    intensity: 0.68,
    dominant_crime_type: "Burglary",
    incident_count: 74,
    peak_window: "Daily 01:00 - 04:00",
  },
  {
    id: "hs-8",
    name: "Vidyaranyapuram Belt",
    district: "Mysuru",
    station_name: "V.V. Puram PS",
    latitude: 12.2958,
    longitude: 76.6394,
    intensity: 0.58,
    dominant_crime_type: "Chain Snatching",
    incident_count: 61,
    peak_window: "Daily 20:00 - 23:00",
  },
  {
    id: "hs-9",
    name: "Old Port Bunder Trading Belt",
    district: "Mangaluru",
    station_name: "Bunder PS",
    latitude: 12.8617,
    longitude: 74.832,
    intensity: 0.91,
    dominant_crime_type: "Organized Extortion",
    incident_count: 119,
    peak_window: "Weekdays 12:00 - 17:00",
  },
  {
    id: "hs-10",
    name: "Hampankatta - Pandeshwar",
    district: "Mangaluru",
    station_name: "Pandeshwar PS",
    latitude: 12.865,
    longitude: 74.842,
    intensity: 0.76,
    dominant_crime_type: "Cyber Fraud",
    incident_count: 103,
    peak_window: "Weekdays 10:00 - 15:00",
  },
  {
    id: "hs-11",
    name: "Kadri - Bejai",
    district: "Mangaluru",
    station_name: "Kadri PS",
    latitude: 12.8894,
    longitude: 74.856,
    intensity: 0.73,
    dominant_crime_type: "Burglary",
    incident_count: 88,
    peak_window: "Daily 01:00 - 04:00",
  },
  {
    id: "hs-12",
    name: "Vidyanagar Hubballi",
    district: "Hubballi-Dharwad",
    station_name: "Vidyanagar PS",
    latitude: 15.355,
    longitude: 75.13,
    intensity: 0.62,
    dominant_crime_type: "Burglary",
    incident_count: 67,
    peak_window: "Daily 02:00 - 05:00",
  },
  {
    id: "hs-13",
    name: "Belagavi Camp",
    district: "Belagavi",
    station_name: "Camp PS",
    latitude: 15.857,
    longitude: 74.506,
    intensity: 0.49,
    dominant_crime_type: "Assault",
    incident_count: 44,
    peak_window: "Weekends 19:00 - 23:00",
  },
  {
    id: "hs-14",
    name: "Brahmapur Kalaburagi",
    district: "Kalaburagi",
    station_name: "Brahmapur PS",
    latitude: 17.335,
    longitude: 76.834,
    intensity: 0.55,
    dominant_crime_type: "Burglary",
    incident_count: 52,
    peak_window: "Daily 02:00 - 04:00",
  },
];

export const MOCK_NETWORK_NODES: NetworkNode[] = [
  {
    id: "nn-1",
    node_id: "S-1042",
    label: "Ravi Kumar",
    node_type: "suspect",
    district: "Bengaluru Urban",
    pos_x: 300,
    pos_y: 190,
    linked_nodes: ["V-01", "L-01", "T-01", "T-03", "S-2213", "S-4471"],
    suspect_code: "S-1042",
  },
  {
    id: "nn-2",
    node_id: "S-2213",
    label: "Imran Sheikh",
    node_type: "suspect",
    district: "Mysuru",
    pos_x: 640,
    pos_y: 170,
    linked_nodes: ["V-02", "L-02", "T-01", "S-1042"],
    suspect_code: "S-2213",
  },
  {
    id: "nn-3",
    node_id: "S-3390",
    label: "Prakash Devadiga",
    node_type: "suspect",
    district: "Mangaluru",
    pos_x: 500,
    pos_y: 380,
    linked_nodes: ["V-03", "T-02", "L-03", "S-8891"],
    suspect_code: "S-3390",
  },
  {
    id: "nn-4",
    node_id: "S-4471",
    label: "Satish Murthy",
    node_type: "suspect",
    district: "Bengaluru Urban",
    pos_x: 180,
    pos_y: 390,
    linked_nodes: ["V-04", "T-04", "L-04", "S-1042", "S-8891"],
    suspect_code: "S-4471",
  },
  {
    id: "nn-5",
    node_id: "S-5514",
    label: "Nagesh Gowda",
    node_type: "suspect",
    district: "Bengaluru Urban",
    pos_x: 420,
    pos_y: 110,
    linked_nodes: ["V-05", "T-05", "L-05"],
    suspect_code: "S-5514",
  },
  {
    id: "nn-6",
    node_id: "S-6620",
    label: "Rehman Pasha",
    node_type: "suspect",
    district: "Mysuru",
    pos_x: 780,
    pos_y: 300,
    linked_nodes: ["V-06", "T-06", "L-02"],
    suspect_code: "S-6620",
  },
  {
    id: "nn-7",
    node_id: "S-7702",
    label: "Suresh Shetty",
    node_type: "suspect",
    district: "Mangaluru",
    pos_x: 300,
    pos_y: 500,
    linked_nodes: ["V-07", "T-07", "L-03"],
    suspect_code: "S-7702",
  },
  {
    id: "nn-8",
    node_id: "S-8891",
    label: "Lokesh Bhat",
    node_type: "suspect",
    district: "Mangaluru",
    pos_x: 680,
    pos_y: 470,
    linked_nodes: ["V-08", "T-04", "L-03", "S-3390"],
    suspect_code: "S-8891",
  },
  {
    id: "nn-9",
    node_id: "V-01",
    label: "Victim · FIR/WFD/2026/2211",
    node_type: "victim",
    district: "Bengaluru Urban",
    pos_x: 160,
    pos_y: 100,
    linked_nodes: ["S-1042"],
    suspect_code: null,
  },
  {
    id: "nn-10",
    node_id: "V-02",
    label: "Victim · FIR/DVR/2026/0781",
    node_type: "victim",
    district: "Mysuru",
    pos_x: 760,
    pos_y: 90,
    linked_nodes: ["S-2213"],
    suspect_code: null,
  },
  {
    id: "nn-11",
    node_id: "V-03",
    label: "Victim · FIR/BUN/2026/0339",
    node_type: "victim",
    district: "Mangaluru",
    pos_x: 560,
    pos_y: 300,
    linked_nodes: ["S-3390"],
    suspect_code: null,
  },
  {
    id: "nn-12",
    node_id: "V-04",
    label: "Victim · FIR/CYB/2026/1120",
    node_type: "victim",
    district: "Bengaluru Urban",
    pos_x: 80,
    pos_y: 320,
    linked_nodes: ["S-4471"],
    suspect_code: null,
  },
  {
    id: "nn-13",
    node_id: "V-05",
    label: "Victim · FIR/KOR/2026/0442",
    node_type: "victim",
    district: "Bengaluru Urban",
    pos_x: 430,
    pos_y: 30,
    linked_nodes: ["S-5514"],
    suspect_code: null,
  },
  {
    id: "nn-14",
    node_id: "V-06",
    label: "Victim · FIR/VVP/2026/0131",
    node_type: "victim",
    district: "Mysuru",
    pos_x: 860,
    pos_y: 230,
    linked_nodes: ["S-6620"],
    suspect_code: null,
  },
  {
    id: "nn-15",
    node_id: "V-07",
    label: "Victim · FIR/KDR/2026/0090",
    node_type: "victim",
    district: "Mangaluru",
    pos_x: 170,
    pos_y: 540,
    linked_nodes: ["S-7702"],
    suspect_code: null,
  },
  {
    id: "nn-16",
    node_id: "V-08",
    label: "Victim · FIR/PDS/2026/0219",
    node_type: "victim",
    district: "Mangaluru",
    pos_x: 810,
    pos_y: 520,
    linked_nodes: ["S-8891"],
    suspect_code: null,
  },
  {
    id: "nn-17",
    node_id: "L-01",
    label: "Whitefield Hotspot",
    node_type: "location",
    district: "Bengaluru Urban",
    pos_x: 380,
    pos_y: 250,
    linked_nodes: ["S-1042", "T-01"],
    suspect_code: null,
  },
  {
    id: "nn-18",
    node_id: "L-02",
    label: "Devaraja Market",
    node_type: "location",
    district: "Mysuru",
    pos_x: 700,
    pos_y: 230,
    linked_nodes: ["S-2213", "S-6620", "T-01"],
    suspect_code: null,
  },
  {
    id: "nn-19",
    node_id: "L-03",
    label: "Bunder Trading Belt",
    node_type: "location",
    district: "Mangaluru",
    pos_x: 450,
    pos_y: 460,
    linked_nodes: ["S-3390", "S-7702", "S-8891"],
    suspect_code: null,
  },
  {
    id: "nn-20",
    node_id: "L-04",
    label: "Cybercrime Cell Zone",
    node_type: "location",
    district: "Bengaluru Urban",
    pos_x: 110,
    pos_y: 240,
    linked_nodes: ["S-4471", "S-8891"],
    suspect_code: null,
  },
];
